# Site settings
name: Angga Priyatna
title: Angga Priyatna | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://anggaprytn.github.io/
baseurl: ''
email: hello@anggaprytn.com
cover: https://anggaprytn.github.io/img/og.png
logo: https://anggaprytn.github.io/img/emojis/technologist.png
resume: https://anggaprytn.github.io/resume.pdf
social:
  - title: email
    url: mailto:hello@anggaprytn.com
  - title: twitter
    url: https://twitter.com/anggaprytn
  - title: instagram
    url: https://instagram.com/anggaprytn
  - title: codepen
    url: http://codepen.io/anggaprytn
  - title: github
    url: https://github.com/anggaprytn
  - title: linkedin
    url: https://www.linkedin.com/in/anggaprytn

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

theme: jekyll-theme-minimal